apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: AUTH_GITHUB_CLIENT_ID
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: AUTH_GITHUB_CLIENT_SECRET
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: GITHUB_TOKEN
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: GITLAB_TOKEN
    - secretKey: AUTH_SECRET
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: AUTH_SECRET
    - secretKey: GITLAB_HOST
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: GITLAB_HOST
    - secretKey:  GITLAB_API_BASE_URL 
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: GITLAB_API_BASE_URL
    - secretKey:  GITLAB_TARGET 
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: GITLAB_TARGET 
    - secretKey: AUTH_GITLAB_CLIENT_ID
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: AUTH_GITLAB_CLIENT_ID
    - secretKey: AUTH_GITLAB_CLIENT_SECRET
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: AUTH_GITLAB_CLIENT_SECRET
    - secretKey: BACKEND_BASE_URL
      remoteRef:
        key: {{ printf "%s-%s-%s-backstage-secrets" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") | default "ew1-test-backstg-backstage-secrets" }}
        property: BACKEND_BASE_URL
