{{- $prefix := printf "%s-%s-%s" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-client-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-client-secret
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-token
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: {{ $prefix }}-backstage-secret-gitlab-token
    - secretKey: AUTH_SECRET
      remoteRef:
        key: {{ $prefix }}-backstage-secret-auth-secret