apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: backstage/secrets
        property: AUTH_GITHUB_CLIENT_ID
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: backstage/secrets
        property: AUTH_GITHUB_CLIENT_SECRET
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage/secrets
        property: GITHUB_TOKEN
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: backstage/secrets
        property: GITLAB_TOKEN
    - secretKey: AUTH_SECRET
      remoteRef:
        key: backstage/secrets
        property: AUTH_SECRET