{{- if index .Values "infra-services" "backstage_github_token" }}
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: backstage
type: Opaque
stringData:
  token: {{ index .Values "infra-services" "backstage_github_token" | quote }}
{{- end }}
