{{- if index .Values "infra-services" "backstage_gitlab_token" }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  namespace: backstage
type: Opaque
stringData:
  token: {{ index .Values "infra-services" "backstage_gitlab_token" | quote }}
{{- end }}
