{{- if .Values.backstage_gitlab_token }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  namespace: backstage
type: Opaque
stringData:
  token: {{ .Values.backstage_gitlab_token | quote }}
{{- end }}
