{{- if .Values.backstageGitlabToken }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  namespace: backstage
type: Opaque
stringData:
  token: {{ .Values.backstageGitlabToken | quote }}
{{- end }}
