{{- $prefix := printf "%s-%s-%s" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: backstage-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ $prefix }}-backstage-postgres-password
    - secretKey: postgres-password
      remoteRef:
        key: {{ $prefix }}-backstage-postgres-password