{{- if .Values.configuration.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  limits:
    cpu: 1k
    memory: 1000Gi
  template:
    metadata:
      labels:
        karpenter/provisioner: default
    spec:
      nodeClassRef:
        name: default
        group: karpenter.k8s.aws
        kind: EC2NodeClass
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
      {{- range .Values.configuration.availabilityZones }}
        - {{ . }}
      {{- end }}
      - key: kubernetes.io/arch
        operator: In
        values:
      {{- range .Values.configuration.arch }}
        - {{ . }}
      {{- end }}
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
      {{- range .Values.configuration.capacityType}}
        - {{ . }}
      {{- end }}
      {{ if .Values.configuration.instanceFamily.enabled}}
      - key: "karpenter.k8s.aws/instance-family"
        operator: In
        values:
      {{- range .Values.configuration.instanceFamily.allowedTypes}}
        - {{ . }}
      {{- end }}
      {{- end }}
{{- end }}
