apiVersion: v2
name: kyverno
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: kyverno-policies
  version: 3.7.0
  repository: https://kyverno.github.io/kyverno/
