{{- if gt (len .Values.jobs) 0 }}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "z-{{ $.Values.appId }}-job-{{ .name }}"
  labels:
    app: "{{ $.Values.appId }}-job-{{ .name }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  template:
    metadata:
      name: "z-{{ $.Release.Name }}-{{ .name }}"
    spec:
      restartPolicy: {{ .restartPolicy }}
      {{- if or ( eq .serviceAccount.enabled true) (eq $.Values.serviceAccount.applyToJob true) }}
      serviceAccountName: {{ printf "%s-job" $.Values.serviceAccount.name | default .serviceAccount.name }}
      {{- end }}
      containers:
      - name: "{{ $.Values.appId }}-job-{{ .name }}"
        {{- if ne $.Values.jobsTagOverride "" }}
        image: "{{ .image.ecr }}/{{ .image.repository }}:{{ $.Values.jobsTagOverride }}"
        {{- else }}
        image: "{{ .image.ecr }}/{{ .image.repository }}:{{ .image.tag }}"
        {{- end }}
        {{- if .command.override }}
        command:
{{ toYaml .command.args | indent 10 }}
        {{- end }}
        {{- if gt (len .env) 0 }}
        env:
          {{- range $key, $val := .env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        {{- if and (eq $.Values.cm.enabled true) (eq .envFromCM true) }}
        envFrom:
        - configMapRef:
            name: "{{ $.Values.appId }}-job"
        {{- end }}
        {{- if eq $.Values.externalsecretEnv.enabled true }}
        - secretRef:
            name: {{ $.Values.appId }}-external-secret
        {{- end }}
        {{- if gt (len .volumes.cm) 0 }}
        volumeMounts:
          {{- range $i, $vol := .volumes.cm }}
          - name: {{ $vol.volName }}
            mountPath: {{ $vol.mountPath }}
          {{- end }}
        {{- end }}
      {{- if gt (len .volumes.cm) 0 }}
      volumes:
        {{- range $i, $vol := .volumes.cm }}
        - name: {{ $vol.volName }}
          configMap:
            name: {{ $vol.cmName }}
        {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
