karpenter:
  fullnameOverride: "karpenter"
  serviceAccount:
    create: true
    name: "karpenter"
    annotations: ""
  replicas: 2
  settings:
    clusterName: ""
    clusterEndpoint: ""
    interruptionQueue: ""
configuration:
  # Set to true if you want default nodepool, and nodeclass resources deployed
  enabled: true
  # Default nodepool settings
  availabilityZones: []
  arch:
    - amd64
  capacityType:
    - spot
    - on-demand
  # Default ec2nodeclass settings
  amiFamily: AL2
  nodeRole: ""
  subnetIDs: []
  securityGroupIDs: []
  securityGroupNames: []
  tags:
    test: test-123:456
