{{- if index .Values "infra-services" "demo_app_enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x-k8s-redis-pop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: pop-dev
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      releaseName: x-k8s-redis
      valueFiles:
      - values.yaml
      - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
    path: helm/redis
    repoURL:  {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true
{{- end }}